# Always check the powershell script for double quotes

stages:
  - run_script

.deploy_template: &deploy_template
    variables:
        liveBranchName: "Development"
        uatBranchName: "UAT"
        developmentBranchName: "main"
        testBranchName: "Test"
        publishProfilesPath: "$CI_PROJECT_DIR/PresentationLayer/App_Data/PublishProfiles"
        deploymentOutput: ""
        gitCompareCommand: "git diff --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" # can add --ignore-all-space to ignore all whitespace
    script:
        - powershell -executionpolicy bypass -File "C:\GitLabRunner\CICD-Scripts\powershell-deployment.ps1"
            -projectName "$CI_PROJECT_NAME"
            -branchName "$CI_COMMIT_REF_NAME"
            -projectPath "$CI_PROJECT_DIR"
            -csprojFile "$CI_PROJECT_DIR/RFC_CODE.sln"
            -apiURL "$CI_API_V4_URL" 
            -projectID "$CI_PROJECT_ID" 
            -liveBranchName $liveBranchName 
            -livePublishProfile "FolderProfile_LIVE_DAIICT.pubxml,FolderProfile_LIVE_DCH.pubxml,FolderProfile_LIVE_HITS.pubxml,FolderProfile_LIVE_IPER.pubxml,FolderProfile_LIVE_IPR.pubxml,FolderProfile_LIVE_MAHER.pubxml,FolderProfile_LIVE_PCEN.pubxml,FolderProfile_LIVE_PRMCEM.pubxml,FolderProfile_LIVE_PRMITR.pubxml,FolderProfile_LIVE_SIMS.pubxml" 
            -liveMachineName "daiict-app,prmitr-app,hits-app,prmitr-app,prmitr-app,mserprfc-app,mserprfc-app,prmitr-app,prmitr-app,MSERPDEMOSERVER"
            -uatBranchName $uatBranchName 
            -uatPublishProfile "FolderProfile_UAT_DAIICT.pubxml,FolderProfile_UAT_DCH.pubxml,FolderProfile_UAT_HITS.pubxml,FolderProfile_UAT_IPER.pubxml,FolderProfile_UAT_IPR.pubxml,FolderProfile_UAT_MAHER.pubxml,FolderProfile_UAT_PCEN.pubxml,FolderProfile_UAT_PRMCEM.pubxml,FolderProfile_UAT_PRMITR.pubxml"
            -uatMachineName "daiict-app,RFCDEV-APP,hits-app,RFCDEV-APP,RFCDEV-APP,mserprfc-app,mserprfc-app,RFCDEV-APP,RFCDEV-APP,RFCDEV-APP"
            -developmentBranchName $developmentBranchName 
            -devPublishProfile "FolderProfile_DEV_RFCDEV"
            -devMachineName "RFCDEV-APP" 
            -testBranchName $testBranchName
            -testPublishProfile "FolderProfile_TEST_RFCTEST"
            -testMachineName "RFCDEV-APP"
            -restorePreviousWebConfig "true" 
            -minutesForDeployment 50
            -applicationType "ASP"
            -aspCSPROJFile "$CI_PROJECT_DIR/BusinessLogicLayer/BusinessLogicLayer.csproj,$CI_PROJECT_DIR/HostelBusinessLogicLayer/HostelBusinessLogicLayer.csproj,$CI_PROJECT_DIR/NonAcadBusinessLogicLayer/NonAcadBusinessLogicLayer.csproj"
            -aspDLLCopyToFilePath "$CI_PROJECT_DIR/PresentationLayer/Bin"
            -restoreFromBackupFiles "/image" 
            -deleteAfterPublishFiles "/APP_CODE,/website.publishproj" 
            -publishPrecompilePath "$CI_PROJECT_DIR\PrecompiledWeb\PresentationLayer\"   
            -restoreDefaultFile "true"
        
    rules:
        - if: '$CI_COMMIT_MESSAGE =~ /See merge request/'


# job_SidDesktop: # for test purposes only
#     stage: run_script
#     tags: 
#         - SidDesktop    
#     <<: *deploy_template    

job_RFC-DEVAPP:
  stage: run_script
  tags: 
    - RFC-DEVAPP
  <<: *deploy_template

job_simsdemo-app:
  stage: run_script
  tags: 
    - simsdemo-app
  <<: *deploy_template

job_hits-app:
  stage: run_script
  tags: 
    - hits-app
  <<: *deploy_template

job_daiict-app:
  stage: run_script
  tags: 
    - daiict-app
  <<: *deploy_template

job_mserprfc-app:
  stage: run_script
  tags: 
    - mserprfc-app
  <<: *deploy_template

job_prmitra-app:
  stage: run_script
  tags: 
    - prmitra-app
  <<: *deploy_template



