# Always check the powershell script for double quotes

stages:
  - run_script

.deploy_template: &deploy_template
    variables:
        liveBranchName: "main"
        uatBranchName: "UAT"
        developmentBranchName: "Development"
        testBranchName: "Test"
        publishProfilesPath: "$CI_PROJECT_DIR/PresentationLayer/App_Data/PublishProfiles"
        deploymentOutput: ""
        gitCompareCommand: "git diff --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" # can add --ignore-all-space to ignore all whitespace
    script:
        - powershell -executionpolicy bypass -File "C:\GitLabRunner\CICD-Scripts\powershell-deployment.ps1"
            -projectName "$CI_PROJECT_NAME"
            -branchName "$CI_COMMIT_REF_NAME"
            -projectPath "$CI_PROJECT_DIR"
            -csprojFile "$CI_PROJECT_DIR/RFC_CODE.sln"
            -apiURL "$CI_API_V4_URL" 
            -projectID "$CI_PROJECT_ID" 
            -liveBranchName $liveBranchName 
            -livePublishProfile "$publishProfilesPath/FolderProfile_LIVE_DAIICT.pubxml,$publishProfilesPath/FolderProfile_LIVE_DCH.pubxml,$publishProfilesPath/FolderProfile_LIVE_HITS.pubxml,$publishProfilesPath/FolderProfile_LIVE_IPER.pubxml,$publishProfilesPath/FolderProfile_LIVE_IPR.pubxml,$publishProfilesPath/FolderProfile_LIVE_MAHER.pubxml,$publishProfilesPath/FolderProfile_LIVE_PCEN.pubxml,$publishProfilesPath/FolderProfile_LIVE_PRMCEM.pubxml,$publishProfilesPath/FolderProfile_LIVE_PRMITR.pubxml,$publishProfilesPath/FolderProfile_LIVE_SIMS.pubxml,$publishProfilesPath/FolderProfile_LIVE_CPUH.pubxml,$publishProfilesPath/FolderProfile_LIVE_CPUKOTA.pubxml,$publishProfilesPath/FolderProfile_LIVE_CRESCENT.pubxml,$publishProfilesPath/FolderProfile_LIVE_MITAOE.pubxml,$publishProfilesPath/FolderProfile_LIVE_RCPIPER.pubxml,$publishProfilesPath/FolderProfile_LIVE_RCPIT.pubxml,$publishProfilesPath/FolderProfile_LIVE_JECRC.pubxml,
$publishProfilesPath/FolderProfile_LIVE_PJLCE.pubxml,$publishProfilesPath/FolderProfile_LIVE_ADCET.pubxml" 
            -liveMachineName "daiict-app,prmitra-app,hits-app,prmitra-app,prmitra-app,mserp-app,mserp-app,prmitra-app,prmitra-app,MSERPDEMOSERVER,CPLKOTA-APP,CPLKOTA-APP,CRESCENT-APPSER,mitaoe-app,RCPITAPPSERVER,RCPITAPPSERVER,JECRCU-APP,mserp-app,mserp-app"
            -uatBranchName $uatBranchName 
            -uatPublishProfile "$publishProfilesPath/FolderProfile_UAT_DAIICT.pubxml,$publishProfilesPath/FolderProfile_UAT_DCH.pubxml,$publishProfilesPath/FolderProfile_UAT_HITS.pubxml,$publishProfilesPath/FolderProfile_UAT_IPER.pubxml,$publishProfilesPath/FolderProfile_UAT_IPR.pubxml,$publishProfilesPath/FolderProfile_UAT_MAHER.pubxml,$publishProfilesPath/FolderProfile_UAT_PCEN.pubxml,$publishProfilesPath/FolderProfile_UAT_PRMCEM.pubxml,$publishProfilesPath/FolderProfile_UAT_PRMITR.pubxml,$publishProfilesPath/FolderProfile_UAT_RCPIT.pubxml,$publishProfilesPath/FolderProfile_UAT_RCPIPER.pubxml,$publishProfilesPath/FolderProfile_UAT_CRESCENT.pubxml,$publishProfilesPath/FolderProfile_UAT_JECRC.pubxml,$publishProfilesPath/FolderProfile_UAT_CPUKOTA.pubxml,$publishProfilesPath/FolderProfile_UAT_CPUH.pubxml,$publishProfilesPath/FolderProfile_UAT_MITAOE.pubxml,$publishProfilesPath/FolderProfile_UAT_RFCDEV.pubxml,$publishProfilesPath/FolderProfile_UAT_PJLCE.pubxml,$publishProfilesPath/FolderProfile_UAT_ADCET.pubxml,$publishProfilesPath/FolderProfile_UAT_TGPCET.pubxml"
            -uatMachineName "daiict-app,RFC-DEVAPP,hits-app,RFC-DEVAPP,RFC-DEVAPP,mserp-app,mserp-app,RFC-DEVAPP,RFC-DEVAPP,RFC-DEVAPP,RFC-DEVAPP,CRESCENT-APPSER,RFC-DEVAPP,RFC-DEVAPP,RFC-DEVAPP,RFC-DEVAPP,RFC-DEVAPP,RFC-DEVAPP,mserp-app,mserp-app"
            -developmentBranchName $developmentBranchName 
            -devPublishProfile "$publishProfilesPath/FolderProfile_DEV_RFCDEV.pubxml"
            -devMachineName "RFC-DEVAPP" 
            -testBranchName $testBranchName
            -testPublishProfile "$publishProfilesPath/FolderProfile_TEST_RFCTEST.pubxml"
            -testMachineName "RFC-DEVAPP"
            -restorePreviousWebConfig "true" 
            -minutesForDeployment 50
            -applicationType "ASP"
            -aspCSPROJFile "$CI_PROJECT_DIR/BusinessLogicLayer/BusinessLogicLayer.csproj,$CI_PROJECT_DIR/HostelBusinessLogicLayer/HostelBusinessLogicLayer.csproj,$CI_PROJECT_DIR/NonAcadBusinessLogicLayer/NonAcadBusinessLogicLayer.csproj"
            -aspDLLCopyToFilePath "$CI_PROJECT_DIR/PresentationLayer/Bin"
            -restoreFromBackupFiles "/image" 
            -deleteAfterPublishFiles "/APP_CODE,/website.publishproj" 
            -publishPrecompilePath "$CI_PROJECT_DIR\PrecompiledWeb\PresentationLayer\"   
            -restoreDefaultFile "true"
        
    rules:
        - if: '$CI_COMMIT_MESSAGE =~ /See merge request/'


# job_SidDesktop: # for test purposes only
#     stage: run_script
#     tags: 
#         - SidDesktop    
#     <<: *deploy_template    

job_RFC-DEVAPP:
  stage: run_script
  tags: 
    - RFC-DEVAPP
  <<: *deploy_template

job_simsdemo-app:
  stage: run_script
  tags: 
    - simsdemo-app
  <<: *deploy_template

job_hits-app:
  stage: run_script
  tags: 
    - hits-app
  <<: *deploy_template

job_daiict-app:
  stage: run_script
  tags: 
    - daiict-app
  <<: *deploy_template

job_mserp-app-rfc-shared:
  stage: run_script
  tags: 
    - mserp-app-rfc-shared
  <<: *deploy_template

job_prmitra-app:
  stage: run_script
  tags: 
    - prmitra-app
  <<: *deploy_template


job_RCPITAPPSERVER:
  stage: run_script
  tags: 
    - RCPITAPPSERVER
  <<: *deploy_template

job_CPLKOTA-APP:
  stage: run_script
  tags: 
    - CPLKOTA-APP
  <<: *deploy_template

job_CRESCENT-APPSER:
  stage: run_script
  tags: 
    - CRESCENT-APPSER
  <<: *deploy_template

job_mitaoe-app:
  stage: run_script
  tags: 
    - mitaoe-app
  <<: *deploy_template

job_JECRCU-APP:
  stage: run_script
  tags: 
    - JECRCU-APP
  <<: *deploy_template


